---

exclude:
  - vendor/*
  - node_modules/*

linters:

  # NOTE: Эти файлы содержат скрипты и сырой текст
  LineLength:
    max: 180
    exclude:
      - app/views/web/pages/*.slim
      - app/views/web/home/_reviews.*.html.slim
      - app/views/layouts/deps/_rollbar.html.slim
