---

extends:
  - stylelint-config-recommended-scss
  # - stylelint-config-twbs-bootstrap/scss

rules:
  # новый scss советует делать @extend через %placeholder, но бутстрап пока не умеет в них
  # https://github.com/twbs/bootstrap/issues/33861 - ждем что-то такое
  scss/at-extend-no-missing-placeholder: null
