---

version: '3'

services:

  redis:
    image: redis
    volumes:
      - redis:/data

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: "make start"
    env_file:
      - .env
    volumes:
      - ~/.bash_history:/root/.bash_history
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - code_data:/var/tmp/hexletbasics
      - app_data:/app/tmp
    depends_on:
      - solargraph
      - spring

  # https://github.com/neoclide/coc-solargraph#configuration-options
  # external server
  solargraph:
    build: .
    command: "bundle exec solargraph socket --host=0.0.0.0 --port=7658"
    ports:
      - "7658:7658"
    env_file:
      - .env
    volumes:
      - ./:/app
      - app_data:/app/tmp

  spring:
    build: .
    command: bin/spring server
    pid: host
    env_file:
      - .env
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - app_data:/app/tmp

  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
      - app_data:/app/tmp
      - app_data:/var/tmp/hexletbasics
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    depends_on:
      - spring
      - redis
      - web

  frontend:
    build: .
    command: make frontend
    # ports:
    #   - "0.0.0.0:3035:3035"
    env_file:
      - .env
    volumes:
      - app_data:/app/tmp
      - .:/app

  caddy:
    image: caddy:2.4.6
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./public:/etc/caddy/public"
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

volumes:
  redis:
  caddy_data:
  caddy_config:
  app_data:
  code_data:
