---

version: '3'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    image: hexletbasics/services-app
    command: make ci-check
    depends_on:
      - postgres

  webserver:
    build:
      context: .
      dockerfile: services/web-nginx/Dockerfile
    ports:
      - "443:443"
      - "80:80"
    # volumes:
      # - "./services/caddy/Caddyfile:/etc/caddy/Caddyfile"
      # - "./public:/etc/caddy/public"
      # - caddy_data:/data
      # - caddy_config:/config
    depends_on:
      - web

  # production:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.production
  #   env_file:
  #     - .env

volumes:
  pgdata:
