# apiVersion: v1
# kind: Service
# metadata:
#   name: "{{ .Release.Name }}-frontend-service"
#   labels:
#     app.kubernetes.io/name: "{{ .Chart.Name }}"
#     app.kubernetes.io/instance: "{{ .Release.Name }}"
#     app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
#     app.kubernetes.io/managed-by: "{{ .Release.Service }}"

# spec:
#   selector:
#     app.kubernetes.io/name: "{{ .Release.Name }}-web-pod"
#   ports:
#     - name: app-listener
#       protocol: TCP
#       port: 80
#       targetPort: 8080
#   type: LoadBalancer
