# -*- mode: yaml; vault: true; -*-
---

hexlet_basics_vault_github_client_id: "a810ed692c0f84251d52"
hexlet_basics_vault_github_client_secret: "e0e8ee70767b0f4d36f88d483ee80b6e9a370dd1"
hexlet_basics_vault_facebook_client_id: "421592815347082"
hexlet_basics_vault_facebook_client_secret: "05e0272e68a45aac9e96129a3f89ebc1"
hexlet_basics_vault_db_hostname: "db"
hexlet_basics_vault_db_username: "postgres"
hexlet_basics_vault_db_pool_size: 2
hexlet_basics_vault_db_password: ""
hexlet_basics_vault_db_name: "hexlet_basics_dev"
hexlet_basics_vault_db_port: "5432"
hexlet_basics_vault_db_ssl_mode: "false"
hexlet_basics_vault_secret_key_base: "NevergonnagiveyouupNevergonnaletyoudownNevergonnarunaroundanddesertyouNevergonnamakeyoucryNevergonnasaygoodbyeNevergonnatellalieandhurtyou"

hexlet_basics_vault_sparkpost_smtp_username: "sparkpost"
hexlet_basics_vault_sparkpost_smtp_password: "password"
hexlet_basics_vault_guardian_secret_key: "asdfasdfasdfasdf"
hexlet_basics_vault_sentry_dsn: "lalajopa"

hexlet_basics_vault_do_spaces_access_id: "lala"
hexlet_basics_vault_do_spaces_secret_key: "xxxx"
hexlet_basics_vault_do_spaces_region: "ams1"
hexlet_basics_vault_do_spaces_sitemap_bucket: "sitemap-bucket-name"
