alloy:
  configMap:
    create: true
    content: |
      logging {
        level  = "warn"
        format = "logfmt"
      }

      remote.kubernetes.secret "alloy" {
        name = "grafana-alloy-secrets"
        namespace = "default"
      }

      prometheus.exporter.unix "node" {
        rootfs_path = "/rootfs"
        procfs_path = "/rootfs/proc"
      }

      prometheus.scrape "node" {
        targets = prometheus.exporter.unix.node.targets
        forward_to = [prometheus.relabel.node.receiver]
      }

      prometheus.relabel "node" {
        forward_to = [prometheus.remote_write.default.receiver]

        rule {
          source_labels = ["instance"]
          regex = "(.*)"
          target_label = "instance"
          replacement = "hb-twc-${1}"
        }
      }

      prometheus.exporter.postgres "database" {
        data_source_names = [remote.kubernetes.secret.alloy.data["db_url"]]
      }

      prometheus.scrape "database" {
        targets = prometheus.exporter.postgres.database.targets
        forward_to = [prometheus.relabel.database.receiver]
      }

      prometheus.relabel "database" {
        forward_to = [prometheus.remote_write.default.receiver]

        rule {
          source_labels = ["instance"]
          regex = "(.*)"
          target_label = "instance"
          replacement = "hb-postgresql"
        }
      }

      prometheus.remote_write "default" {
        endpoint {
          url = convert.nonsensitive(remote.kubernetes.secret.alloy.data["receiver_url"])

          basic_auth {
            username = convert.nonsensitive(remote.kubernetes.secret.alloy.data["receiver_username"])
            password = remote.kubernetes.secret.alloy.data["receiver_password"]
          }
        }
      }

  mounts:
    extra:
      - name: host-root
        mountPath: /rootfs
        readOnly: true
      - name: host-proc
        mountPath: /rootfs/proc
        readOnly: true
      - name: host-sys
        mountPath: /sys
        readOnly: true

controller:
  volumes:
    extra:
      - name: host-root
        hostPath:
          path: /
      - name: host-proc
        hostPath:
          path: /proc
      - name: host-sys
        hostPath:
          path: /sys
