development:
  app_url_en: 'http://en.code-basics.test'
  app_url_ru: 'http://ru.code-basics.test'

production:
  app_url_en: 'https://code-basics.com'
  app_url_ru: 'https://ru.code-basics.com'

test:
  app_url_en: 'http://en.code-basics.test'
  app_url_ru: 'http://ru.code-basics.test'
