---
# <% group = "{en,ru,es}" %>

translations:
  - file: app/javascript/generated/locales.json
    patterns:
      - "{ru,en,es}.*"
      - "!*.faker.*"
      # - "!*.errors"
      # - "!*.number.nth"
