---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "{{.Release.Name }}-ingress"
  namespace: "{{ .Release.Namespace }}"
  annotations:
    ingress.alb.yc.io/external-ipv4-address: '89.169.182.43'
    ingress.alb.yc.io/subnets: 'e2lfircmrq1atgmlg7ib'
    ingress.alb.yc.io/group-name: 'codebasics-ingress-group'
    ingress.alb.yc.io/upgrade-types: 'websocket'

spec:
  tls:
    - hosts:
        - code-basics.com
      secretName: yc-certmgr-cert-id-fpqgjl11q387a86d42kn

  rules:
    - host: "*.code-basics.com"
      http:
        paths:
          - path: "/ru/api/lessons/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-check-service"
                port:
                  number: 80
          - path: "/api/lessons/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-check-service"
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-service"
                port:
                  number: 80

    - host: "code-basics.ru"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-service"
                port:
                  number: 80

    # NOTE: должно быть отдельно, несмотря на то что выше есть *.code-basics.com
    # так как иначе не будет создан роут в лоад балансере для tls
    - host: "code-basics.com"
      http:
        paths:
          - path: "/ru/api/lessons/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-check-service"
                port:
                  number: 80
          - path: "/api/lessons/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-check-service"
                port:
                  number: 80
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: "{{.Release.Name }}-web-service"
                port:
                  number: 80
