---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-job-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-job-pod"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-job-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-job-pod"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        code-basics/web-pod: "{{ .Release.Name }}-{{ .Values.version }}-job-pod"

    spec:
      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-secret
          secret:
            secretName: docker-config
            items:
              - key: .dockerconfigjson
                path: config.json

      containers:
        - name: sidekiq
          imagePullPolicy: Always
          image: "{{ .Values.web.image.repository }}:{{ .Values.version }}"
          resources:
            requests:
              memory: 300Mi
              cpu: 10m
            limits:
              memory: 600Mi
          command: ["bundle", "exec", "sidekiq"]
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - name: docker-secret
              mountPath: /root/.docker
          envFrom:
            - secretRef:
                name: hexlet-basics-environment-secrets
          env:
            - name: HEXLET_BASICS_RELEASE_VERSION
              value: {{ .Values.version }}
