---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-job-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Release.Name }}-job-pod"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-job-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  strategy:
    # type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-job-pod"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        code-basics/web-pod: "{{ .Release.Name }}-{{ .Values.version }}-job-pod"

    spec:
      imagePullSecrets:
        - name: docker-config

      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
        - name: docker-secret
          secret:
            secretName: docker-config
            items:
              - key: .dockerconfigjson
                path: config.json
      containers:
        - name: sidekiq
          securityContext:
            privileged: true
          imagePullPolicy: "{{ .Values.web.image.imagePullPolicy }}"
          image: "{{ .Values.web.image.repository }}:{{ .Values.version }}"
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 20m
          command: ["bundle", "exec", "sidekiq"]
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path
            - mountPath: /var/run/docker.sock
              name: docker-sock
            - name: docker-secret
              mountPath: /root/.docker
          envFrom:
            - secretRef:
                name: hexlet-basics-secrets
            - secretRef:
                name: github-credentials
            - secretRef:
                name: facebook-credentials
            - secretRef:
                name: sparkpost-credentials
            - configMapRef:
                name: hexlet-basics-config-map
          env:
            - name: CODE_BASICS_VERSION
              value: {{ .Values.version }}
          lifecycle:
            postStart:
              exec:
                command: {{ .Values.slack_notification }}
