apiVersion: v1
kind: Secret
metadata:
  name: "docker-config"
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.docker.config | b64enc | quote }}
