apiVersion: v1
kind: Secret
metadata:
  name: "codebasics-environment-secrets"
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets.code_basics.env }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
