---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-ssr-deployment"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

spec:
  replicas: 4

  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-ssr-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-ssr-pod"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        codebasics/pod: "{{ .Release.Name }}-{{ .Values.version }}-ssr-pod"
    spec:
      nodeSelector:
        group: "{{ .Release.Namespace }}"

      imagePullSecrets:
        - name: docker-config

      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: "codebasics/pod"
                      operator: In
                      values:
                        - "{{ .Release.Name }}-{{ .Values.version }}-ssr-pod"
                topologyKey: "kubernetes.io/hostname"

      containers:
        - name: ssr
          imagePullPolicy: Always
          image: "{{ .Values.app.image.repository }}:{{ .Values.version }}"
          command: ["bin/vite", "ssr"]
          startupProbe:
            httpGet:
              path: /health
              port: 13714
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 13714
            initialDelaySeconds: 5
            periodSeconds: 8
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 13714
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
          ports:
            - containerPort: 13714
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 400Mi
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: codebasics-environment-secrets
                  key: NODE_ENV
            - name: NODE_OPTIONS
              value: "--max-old-space-size=256"
