---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-ssr-b-deployment"
  namespace: "{{ .Release.Namespace }}"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

spec:
  replicas: 2

  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-ssr-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-ssr-pod"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        codebasics/pod: "{{ .Release.Name }}-{{ .Values.version }}-ssr-b-pod"
    spec:
      nodeSelector:
        group: "{{ .Release.Namespace }}"

      imagePullSecrets:
        - name: docker-config

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "codebasics/pod"
                    operator: In
                    values:
                      - "{{ .Release.Name }}-{{ .Values.version }}-ssr-a-pod"
                      - "{{ .Release.Name }}-{{ .Values.version }}-job-pod"
              topologyKey: "kubernetes.io/hostname"

      containers:
        - name: ssr
          imagePullPolicy: Always
          image: "{{ .Values.app.image.repository }}:{{ .Values.version }}"
          command: ["bin/vite", "ssr"]
          startupProbe:
            httpGet:
              path: /health
              port: 13714
            periodSeconds: 5
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /health
              port: 13714
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /health
              port: 13714
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 2
            failureThreshold: 3
          ports:
            - containerPort: 13714
          resources:
            requests:
              memory: 200Mi
              cpu: 100m
            limits:
              memory: 400Mi
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: codebasics-environment-secrets
                  key: NODE_ENV
            - name: NODE_OPTIONS
              value: "--max-old-space-size=192"
