---

apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-web-check-service"
  namespace: "{{ .Release.Namespace }}"
spec:
  selector:
    app.kubernetes.io/name: "{{ .Release.Name }}-web-check-pod"
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
