---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-web-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
    app.kubernetes.io/version: "{{ .Chart.AppVersion }}"
    app.kubernetes.io/managed-by: "{{ .Release.Service }}"

spec:
  replicas: 3

  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Release.Name }}-web-pod"
      app.kubernetes.io/instance: "{{ .Release.Name }}"

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Release.Name }}-web-pod"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        helm.sh/chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}'
        hexlet-basics/web-pod: "{{ .Release.Name }}-{{ .Values.version }}-web-pod"

    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "hexlet-basics/web-pod"
                    operator: In
                    values:
                      - "{{ .Release.Name }}-{{ .Values.version }}-web-pod"
              topologyKey: "kubernetes.io/hostname"

      volumes:
        - name: users-code-path
          hostPath:
            path: /tmp/hexlet-basics
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock

      # TODO: нужно только при первом деплое для смены прав. Закомментировать после первого деплоя
      # initContainers:
      #   - name: volume-permissions
      #     image: busybox
      #     command: ['sh', '-c', 'chown -R 1000:1000 /tmp/hexlet-basics']
      #     volumeMounts:
      #       - mountPath: /tmp/hexlet-basics
      #         name: users-code-path

      containers:
        - name: nginx
          imagePullPolicy: Always
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.version }}"
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 8
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 3
            failureThreshold: 3
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: 30Mi
              cpu: 15m
            limits:
              memory: 100Mi
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "10"]

        - name: web
          imagePullPolicy: Always
          image: "{{ .Values.web.image.repository }}:{{ .Values.version }}"
          startupProbe:
            httpGet:
              path: /up
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /up
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 5
            periodSeconds: 8
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /up
              port: 3000
              httpHeaders:
                - name: X-Forwarded-Proto
                  value: https
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 400Mi
              cpu: 100m
            limits:
              memory: 1200Mi
          volumeMounts:
            - mountPath: /tmp/hexlet-basics
              name: users-code-path
            - mountPath: /var/run/docker.sock
              name: docker-sock
          envFrom:
            - secretRef:
                name: hexlet-basics-environment-secrets
          env:
            - name: HEXLET_BASICS_RELEASE_VERSION
              value: {{ .Values.version }}
          lifecycle:
            postStart:
              exec:
                command: {{ .Values.slack_notification }}
            preStop:
              exec:
                command: ["sleep", "15"]

        - name: ssr
          imagePullPolicy: Always
          image: "{{ .Values.web.image.repository }}:{{ .Values.version }}"
          command: ["bin/vite", "ssr"]
          startupProbe:
            httpGet:
              path: /
              port: 13714
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            httpGet:
              path: /
              port: 13714
            initialDelaySeconds: 5
            periodSeconds: 8
            timeoutSeconds: 2
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 13714
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 3
          ports:
            - containerPort: 13714
          resources:
            requests:
              memory: 300Mi
              cpu: 100m
            limits:
              memory: 1100Mi
          env:
            - name: NODE_ENV
              valueFrom:
                secretKeyRef:
                  name: hexlet-basics-environment-secrets
                  key: NODE_ENV
          lifecycle:
            preStop:
              exec:
                command: ["sleep", "15"]
