---

- hosts: localhost
  gather_facts: false
  tasks:
    - template:
        src: secrets.auto.tfvars.j2
        dest: '../terraform/secrets.auto.tfvars'
    - template:
        src: docker.config.json.j2
        dest: '../terraform/docker-config.json'
