---

- hosts: localhost
  gather_facts: false
  tasks:
    - template:
        src: backend_secrets.auto.tfvars.j2
        dest: "../terraform/backend.secrets.auto.tfvars"

    - template:
        src: secrets.auto.tfvars.j2
        dest: "../terraform/secrets.auto.tfvars"
