---

- hosts: localhost
  gather_facts: false
  tasks:
    - template:
        src: backend_secrets.auto.tfvars.j2
        dest: "../terraform/backend.secrets.auto.tfvars"

    - template:
        src: secrets.auto.tfvars.j2
        dest: "../terraform/secrets.auto.tfvars"

    - copy:
        content: "{{ vault_yc.service_key_data | to_nice_json }}"
        dest: "../terraform/yc_config.json"

    - template:
        src: docker.config.json.j2
        dest: "../terraform/docker-config.json"
