name: docker

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: hexletbasics/hexlet-basics

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          cache-to: type=inline
          # push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - uses: actions/checkout@v2

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit
        env:
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          BUILDKIT_INLINE_CACHE: 1

      - name: Push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'push' }}
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Send notification into Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
