name: pullrequest

on:
  pull_request:
    branches:
      - main

env:
  CI: true
  APP_IMAGE_NAME: hexletbasics/services-app

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - uses: actions/checkout@v3

      - name: Build App
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.production
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          tags: |
            ${{ env.APP_IMAGE_NAME }}:cached
            ${{ env.APP_IMAGE_NAME }}:latest

      - name: Check
        run: |
          make ansible-generate-env
          docker-compose --file docker-compose.yml up --abort-on-container-exit
