name: push

on:
  pull_request:
    branches:
      - master

env:
  IMAGE_NAME: hexletbasics/services-app

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: actions/checkout@v2

      - name: Build App Base
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached-base
          tags: |
            ${{ env.IMAGE_NAME }}:cached-base

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:cached

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit
