name: push

on:
  push:
    branches:
      - main

env:
  VITE_RUBY_AUTO_BUILD: "false"

jobs:
  build:
    # TODO: switch to arm https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
      - run: npm ci

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install

      - run: make lint

      - run: RAILS_ENV=test bin/rails assets:precompile

      - run: make test
