name: push

on:
  push:
    branches:
      - main

# env:
#   CI: true
#   APP_IMAGE_NAME: hexletbasics/services-app
#   NGINX_IMAGE_NAME: hexletbasics/services-nginx
#   COLOR_MAP: '{ success: "#008000", failure: "#800000" }'

jobs:
  build:
    runs-on: ubuntu-latest-arm64
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'
      - run: npm ci

      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install

      - name: Cache assets
        uses: actions/cache@v4
        with:
          path: public/vite-test
          key: test-assets-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/Gemfile.lock', '**/vite.config.ts') }}
          restore-keys: |
            assets-${{ runner.os }}-

      - run: RAILS_ENV=test bin/rails assets:precompile

      - run: make lint
      - run: make test
