name: push

on:
  push:
    branches:
      - master
    tags:
        - 'v*'

env:
  APP_IMAGE_NAME: hexletbasics/services-app
  CADDY_IMAGE_NAME: hexletbasics/services-caddy
  NGINX_IMAGE_NAME: hexletbasics/services-nginx
  COLOR_MAP: '{ success: "#008000", failure: "#800000" }'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          cache-to: type=registry,ref=${{ env.APP_IMAGE_NAME }}:cached
          tags: |
            ${{ env.APP_IMAGE_NAME }}:cached
            ${{ env.APP_IMAGE_NAME }}:latest

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          push: true
          tags: ${{ env.APP_IMAGE_NAME }}:latest

      - name: Build&Push Caddy
        uses: docker/build-push-action@v2
        with:
          context: services/caddy
          file: services/caddy/Dockerfile.production
          push: true
          tags: ${{ env.CADDY_IMAGE_NAME }}:latest

      - name: Build&Push Nginx
        uses: docker/build-push-action@v2
        with:
          context: services/web-nginx
          file: services/web-nginx/Dockerfile.production
          push: true
          tags: ${{ env.NGINX_IMAGE_NAME }}:latest

      - name: Send notification into Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ fromJson(env.COLOR_MAP)[job.status] }}
          SLACK_TITLE: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

  release:

