name: push

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: hexletbasics/services-app
  COLOR_MAP: '{ success: "#800000", failure: "#008000" }'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Build App Base
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached-base
          cache-to: type=inline
          # push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:cached-base

      - name: Build App
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          cache-to: type=inline
          # push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:cached

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          # cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          # cache-to: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Send notification into Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ fromJson(env.COLOR_MAP)[job.status] }}
          SLACK_TITLE: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
