name: push

on:
  push:
    branches:
      - master

env:
  IMAGE_NAME: hexletbasics/services-app
  CADDY_IMAGE_NAME: hexletbasics/services-caddy
  COLOR_MAP: '{ success: "#008000", failure: "#800000" }'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: actions/checkout@v2

      - name: Build App Base
        run: |
          docker build \
            --pull \
            --cache-from ${{ env.IMAGE_NAME }}:cached-base2 \
            --tag ${{ env.IMAGE_NAME }}:cached-base2 services/app
          docker push ${{ env.IMAGE_NAME }}:cached-base2

      - name: Build App
        run: |
          docker build \
            --pull \
            --cache-from ${{ env.IMAGE_NAME }}:cached \
            --file services/app/Dockerfile.production \
            --tag ${{ env.IMAGE_NAME }}:cached services/app
          docker push ${{ env.IMAGE_NAME }}:cached

      - name: Check
        run: |
          docker-compose --file docker-compose.yml up --abort-on-container-exit

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: services/app
          file: services/app/Dockerfile.production
          cache-from: type=registry,ref=${{ env.IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest

      - name: Build Caddy
        run: |
          docker build \
            --pull \
            --cache-from ${{ env.CADDY_IMAGE_NAME }}:cached \
            --file services/caddy/Dockerfile.production \
            --tag ${{ env.CADDY_IMAGE_NAME }}:cached services/caddy
          docker push ${{ env.CADDY_IMAGE_NAME }}:cached

      - name: Push
        uses: docker/build-push-action@v2
        with:
          context: services/caddy
          file: services/caddy/Dockerfile.production
          cache-from: type=registry,ref=${{ env.CADDY_IMAGE_NAME }}:cached
          push: true
          tags: ${{ env.CADDY_IMAGE_NAME }}:latest

      - name: Send notification into Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_COLOR: ${{ fromJson(env.COLOR_MAP)[job.status] }}
          SLACK_TITLE: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
