name: release

on:
  push:
    tags:
      - v*

env:
  IMAGE_NAME: hexletbasics/services-app
  RELEASE_IMAGE_NAME: hexletbasics/services-app:${{ github.event.release.tag_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull
        run: docker pull ${{ env.IMAGE_NAME }}

      - name: Tag
        run: docker tag ${{ env.IMAGE_NAME }} ${{ env.RELEASE_IMAGE_NAME }}

      - name: Push
        run: docker push ${{ env.RELEASE_IMAGE_NAME }}

      - name: Send notification into Slack
        if: ${{ always() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_TITLE: ${{ job.status }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
