name: On Release

on:
  push:
    tags:
      - v*

jobs:

  build:
    if: github.repository == 'hexlet-basics/hexlet-basics'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Tag To The Env
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF:10})" >> $GITHUB_ENV

      # - name: Run web tests
      #   run: |
      #     make web-ci-test

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: hexletbasics/services-nginx
          image_tag: ${{ env.RELEASE_VERSION }}
          context: services/web-nginx
          dockerfile: Dockerfile.production

      - uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image_name: hexletbasics/services-app
          image_tag: ${{ env.RELEASE_VERSION }}
          context: services/app
          dockerfile: Dockerfile.production

      - uses: rtCamp/action-slack-notify@v2.0.0
        env:
          SLACK_CHANNEL: '#basics-code-auto'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
